# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target '02 - FBSearch' do
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'FacebookCore'
  pod 'FacebookLogin'
end

target '02 - FBSearchTests' do
  pod 'RxBlocking', '~> 3.0'
  pod 'RxTest',     '~> 3.0'
end
